### PR TITLE
Transport statistics additions

### PR DESCRIPTION
**Pull request by aboba**

### CODE REVIEW

**Review by FrankLi-MS — COMMENTED** [review]
mediaLgeId should be mediaLegId

**Review by FrankLi-MS — COMMENTED** [review]
csntFail should be consentFail. Never mind, it is updated in commit b84f7d2

**Comment by aboba** [comment]
@FrankLi-MS Fixed the typo.

**Comment by aboba** [comment]
Some questions: 

1. Do we have documentation for the values of the IceConnCheckStatus Enum?
2. Is BlobGenTime measured in ms relative to the reference time?

**Comment by aboba** [comment]
Comments:  Can we spell out MDGA?  Pretty sure this does not stand for Minnesota Dairy Goat Association :)

**Review by nileshjavar — APPROVED** [review]

**Pull request merged**
